const Blog = require("../models/Blog");
const Category = require("../models/Category");

// Create a new category
exports.createCategory = async (req, res) => {
  try {
    const { categoryName, activeStatus } = req.body;
    const category = new Category({ categoryName, activeStatus });
    await category.save();
    res.status(201).json(category);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
};

// Get all categories
exports.getAllCategories = async (req, res) => {
  try {
    const categories = await Category.find();
    res.status(200).json(categories);
  } catch (err) {
    res.status(500).json({ error: "Failed to retrieve categories." });
  }
};

// Update a category
exports.updateCategory = async (req, res) => {
  try {
    const { urlKey } = req.params;
    const { categoryName, activeStatus } = req.body;

    // Find the category by urlKey
    const category = await Category.findOne({ urlKey });
    if (!category) return res.status(404).json({ error: "Category not found." });

    // Update category fields
    if (categoryName) category.categoryName = categoryName;
    if (activeStatus) category.activeStatus = activeStatus;

    // urlKey will be regenerated by pre-save hook if categoryName changed
    await category.save();
    
    res.status(200).json(category);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
};

// Delete a category by name
exports.deleteCategoryByName = async (req, res) => {
  try {
    const { categoryName } = req.params;
    const category = await Category.findOneAndDelete({ categoryName: categoryName.toLowerCase() });
    if (!category) return res.status(404).json({ error: "Category not found." });
    res.status(200).json({ message: "Category deleted successfully." });
  } catch (err) {
    res.status(500).json({ error: "Failed to delete category." });
  }
};